apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    version: '2.0'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      version: '2.0'
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nginx
        version: '2.0'
    spec:
      containers:
      - name: nginx
        image: balabhaskararao/bala-hello-2.0:latest
        ports:
        - containerPort: 80
